package com.poobo.sysmanage.tvshow.model;

import java.io.Serializable;
import java.util.Date;

import com.poobo.frame.mapper.BaseMapper;
import com.poobo.sysmanage.member.model.TblAuthInfo;

public class TblTvShow  implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_tv_show.pk_global_id
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	private String pkGlobalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_tv_show.m_date
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	private Date mDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_tv_show.audio
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	private String audio;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_tv_show.pk_global_id
	 * @return  the value of tbl_tv_show.pk_global_id
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	public String getPkGlobalId() {
		return pkGlobalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_tv_show.pk_global_id
	 * @param pkGlobalId  the value for tbl_tv_show.pk_global_id
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	public void setPkGlobalId(String pkGlobalId) {
		this.pkGlobalId = pkGlobalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_tv_show.m_date
	 * @return  the value of tbl_tv_show.m_date
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	public Date getmDate() {
		return mDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_tv_show.m_date
	 * @param mDate  the value for tbl_tv_show.m_date
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	public void setmDate(Date mDate) {
		this.mDate = mDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tbl_tv_show.audio
	 * @return  the value of tbl_tv_show.audio
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	public String getAudio() {
		return audio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tbl_tv_show.audio
	 * @param audio  the value for tbl_tv_show.audio
	 * @mbg.generated  Thu Dec 07 22:01:33 GMT+08:00 2017
	 */
	public void setAudio(String audio) {
		this.audio = audio;
	}
}